### ISSUE TITLE
Crash when opening Video Settings

### ISSUE THREAD

**Issue by InsomniaKitten** [blay09/ClientTweaks#1]
Game crashed when clicking the Video Settings button in the Options screen.

**Forge version:** [12.18.1.2094](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.1.2094/forge-1.10.2-12.18.1.2094-changelog.txt)
**Crash report:** [pastebin.com/4ZvfQ8am](http://pastebin.com/4ZvfQ8am)

**Comment by blay09** [comment]
Uh, that's really weird. Is it reproducable? Works fine for me on the same Forge version both in dev and normal environment.

**Comment by InsomniaKitten** [comment]
Ugh, yanno what, it's probably OptiFine. Forgot to disable it before testing your mod. I'll just disable the 3D Anaglyph tweak when using it. :)

**Comment by MCOfficer** [comment]
@InsomniaKitten fixed with the latest releases, you can enable optifine again ;)
