### ISSUE TITLE
Sound stopped working after installing Client Tweaks

### ISSUE THREAD

**Issue by The-Fireplace** [blay09/ClientTweaks#10]
After installing Client Tweaks 1.11-2.1.2, the sound on my game stopped working. Loaded mods(Minus Client Tweaks):
http://modlister.com/user/The_Fireplace
fml-client-latest.log, when the issue occurred:
http://paste.ubuntu.com/24740436/

**Comment by BlayTheNinth** [comment]
Is this reproducible? Other than the Master Volume Slider there's nothing related to sounds in the mod, and the slider only changes the master volume when it's actually used (and even then it only touches the existing volume option, so there's no real magic happening).

**Comment by The-Fireplace** [comment]
I believe the issue resolved itself after an update. I'll check it tomorrow
to confirm.
