### ISSUE TITLE
Underlines not removed from chat

### ISSUE THREAD

**Issue by Dimentive** [blay09/ClientTweaks#13]
Even though I’ve “Remove Underlines From Chat” enabled, underlines are still visible in the chat.

**Minecraft version**: 1.10.2
**Client Tweaks version**: 1.1.16

**Comment by BlayTheNinth** [comment]
This happens for underlines within messages that are only sent from the client. Sadly Forge refuses to provide an event to react to these messages, making this impossible to fix without getting hacky.

https://github.com/MinecraftForge/MinecraftForge/pull/3245
https://github.com/MinecraftForge/MinecraftForge/pull/2842

**Comment by BlayTheNinth** [comment]
This will become part of Chat Tweaks in the future: https://github.com/blay09/ChatTweaks/issues/58

**Comment by Dimentive** [comment]
@blay09 Cool. Thanks!

**Comment by Dimentive** [comment]
@blay09 Cool. Thanks! 👍
