### ISSUE TITLE
ReWIRED's AEGIS defense Matrix causes "Hide Offhand" to not work

### ISSUE THREAD

**Issue by GuntherDW** [blay09/ClientTweaks#17]
I currently have "hide off-hand" enabled.

However, when you "install" the "AEGIS Defense Matrix" from ReWIRED and enable said augment the off-hand item gets drawn again.
It'll disappear again when you disable the augment.

Cyberware for 1.12.2 is called "Robotic Parts" on CurseForge, but the filenames and everything else is still the same.

Versions:
 - Minecraft: 1.12.2
 - Forge: 14.23.4.2705
 - ClientTweaks: 1.12.2-3.1.8
 - Cyberware: 1.12.2-0.2.10.12
 - ReWIRED: 1.0.3

**Comment by BlayTheNinth** [comment]
This is an issue in ReWIRED, it is rendering the hand regardless of the event (both in the main hand pass), and probably twice if Client Tweaks wouldn't cancel the off hand.

https://github.com/mallrat208/Re-WIRED/blob/bd0701a2fd6d63e42fc94189d48224ef8ed14b93/src/main/java/com/mr208/rewired/common/handlers/EventHandlerClient.java#L240-L261
