### ISSUE TITLE
Suggestion: Place Torches with off hand till you only have 1 torch left in your off hand.

### ISSUE THREAD

**Issue by StoneLegion** [blay09/ClientTweaks#18]
I like the feature of not placing torches but I kind of wish I could place them from time to time. I assume like many people we don't use this option to not place them down EVER but rather we want to make sure we have one on us always for Dynamic Light Mods like Optifine.

So it be nice to be able to place them via an option but keep the last one.

Not sure if this be a great 2nd option or a replacement of the first. Some people might have objections to ever placing any. 

Thanks.

**Comment by BlayTheNinth** [comment]
Similarly to the other offhand torch options, this will not work on servers until #2 is fixed.
