### ISSUE TITLE
Sometimes going up ladders with the auto climber ladder climbing descending feature disabled will make it stutter.

### ISSUE THREAD

**Issue by SirAron111** [blay09/ClientTweaks#21]
Sometimes going up ladders with the auto climber ladder climbing descending feature disabled will make it stutter.

**Comment by BlayTheNinth** [comment]
The Auto Climb feature doesn't do anything when it's disabled so it can't have any negative effect on performance. It sounds more like a general lag issue unrelated to Client Tweaks.

**Comment by SirAron111** [comment]
A I forgot about this ye this is a conflict on iguana tweaks reborn end the weight feature drags you down under water or on ladders auto climb disables this actually which is good as the stuttering is a bug not a feature. https://github.com/Insane96/IguanaTweaksReborn/issues/82
