### ISSUE TITLE
ClientTweaks has failed to load correctly

### ISSUE THREAD

**Issue by 23SRLITheGamer** [blay09/ClientTweaks#25]
net/minecraftforge/client/event/InputEvent$ClickInputEvent

can I get help on this?
These are my mods that am using, and running forge for 1.15.1 (30.0.36)
![moz](https://user-images.githubusercontent.com/16334980/72683583-921ccd80-3b13-11ea-9127-c640e8826949.PNG)

**Comment by BlayTheNinth** [comment]
You have to update to the latest version of Forge.

**Comment by 23SRLITheGamer** [comment]
30.0.41 ver should work?

**Comment by BlayTheNinth** [comment]
Anything after 30.0.40, which is where the ClickInputEvent was added.

**Comment by 23SRLITheGamer** [comment]
alright thanks for the quick response
