### ISSUE TITLE
Torch placement options not working on server/multiplayer

### ISSUE THREAD

**Issue by ghost** [blay09/ClientTweaks#41]
Version: ClientTweaks 1.12.2-3.1.11
 
Thank you for your hard work on this mod!  I'm having a issue with torch placement options.  Do not use last torch, no torch with block in hand, no torch with empty hand, and torch with tool only are not working for me on a multiplayer server which I'm admin of.  They are enabled in the config and work fine in single player.  Is there something else I have to configure to get it to work on a server?

**Comment by BlayTheNinth** [comment]
The torch options only worked in singleplayer on older versions due to Forge limitations. I believe 1.15+ is when they started working in multiplayer as well.
