### ISSUE TITLE
Weird visual glitch

### ISSUE THREAD

**Issue by emanuele246gi** [blay09/ClientTweaks#44]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

38.0.14

### Mod Version

7.0.0

### Describe the Issue

After I've installed this mod, it causes this weird glitch and there is also no sound, not to mention that Minecraft doesn't even appear in the mixer audio of Windo
![Minecraft_ 1 18 05_12_2021 10_58_25](https://user-images.githubusercontent.com/61762317/144742628-59544b1d-1630-449d-ba15-190cb65f2a9a.png)
![Minecraft_ 1 18 05_12_2021 10_53_05](https://user-images.githubusercontent.com/61762317/144742630-cd953667-a2b2-4e28-a59b-42cead90240e.png)
ws

### Logs

Too long, sorry :/

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No

**Comment by BlayTheNinth** [comment]
put logs on pastebin

**Comment by emanuele246gi** [comment]
I said that I can't, it's too long and Pastebin doesn't make it

**Comment by BlayTheNinth** [comment]
then use gist or any other service, or check the logs yourself to find relevant errors, but I can't do anything without logs

**Comment by emanuele246gi** [comment]
https://gist.github.com/emanuele246gi/c2d1e5213832e233e8b4db441f363f4d Here you go

**Comment by BlayTheNinth** [comment]
Unrelated, but Survive is spamming your logs like crazy, you should report that to them separately

Other than that, those are logs from a Minecraft 1.16.5 instance, not 1.18

**Comment by emanuele246gi** [comment]
Wait really? Lol I made a mistake I think

**Comment by emanuele246gi** [comment]
Anyway for that spam they already fixed it in the 1.18 version

**Comment by emanuele246gi** [comment]
I can't do it even on gist... I tried to put the whole file here but it says that "is not included in the list". What do I need to do?

**Comment by BlayTheNinth** [comment]
upload it to some file hosting service

**Comment by emanuele246gi** [comment]
https://www.mediafire.com/file/px18qxemrxmn0m1/latest.log/file Here

**Comment by BlayTheNinth** [comment]
Does it stop happening when you remove Client Tweaks? Does it happen if you run only Client Tweaks (without any other mods)?

Client Tweaks doesn't do anything with rendering on the title screen, so it's most likely some other mod causing it.

**Comment by emanuele246gi** [comment]
Apparently there is also some other mod that does this, but this issue appeared when I installed Client Tweaks too

**Comment by emanuele246gi** [comment]
Okay don't worry, I fixed it by updating Balm, that was weird anyway
