### ISSUE TITLE
NullPointerException when joining server

### ISSUE THREAD

**Issue by evhub** [blay09/ClientTweaks#49]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

39.0.75

### Mod Version

7.0.0

### Describe the Issue

When joining a server (which is running a compatible mod list, but does not have Client Tweaks), the client crashes with the following NullPointerException:
```
java.lang.NullPointerException: Cannot read field "tweaks" because the return value of "net.blay09.mods.clienttweaks.ClientTweaksConfig.getActive()" is null
```

### Logs

https://gist.github.com/kcwoolverton/625ac7e20c60e70580c7c7d8cdf22ffb

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Optifine is not enabled.

**Comment by BlayTheNinth** [comment]
Does this happen with newer versions of Balm?
