### ISSUE TITLE
Crash in Video Settings (v.1.1.11 @1.10.2)

### ISSUE THREAD

**Issue by MCOfficer** [blay09/ClientTweaks#5]
whenever i try to open the video settings, it crashes due to some mipmap slider. optifine is installed, which might be the cause.
log: http://pastebin.com/T8bkyqgn

edit: same error when the mipmap slider is disabled in the clienttweaks.cfg

**Comment by blay09** [comment]
Disable the fix mipmap slider option if you use Optifine.

**Comment by blay09** [comment]
Try http://jenkins.blay09.net/job/Client%20Tweaks%201.10.2/12/

**Comment by MCOfficer** [comment]
**works,** also when enabled in the config. the slider is usable as well.
thanks, and keep it up!
