### ISSUE TITLE
"No offhand torch" not working in servers

### ISSUE THREAD

**Issue by Devrelop** [blay09/ClientTweaks#55]
### Minecraft Version

1.12.x

### Mod Loader

Forge

### Mod Loader Version

14.23.5.2860

### Mod Version

1.12.2-3.1.11

### Describe the Issue

As the title says, torches still get placed when in offhand despite having it disabled. It only happens in servers as this bug does not occur in single player. Do I have to install the mod on the server too?

**Comment by BlayTheNinth** [comment]
This option was only supported in singleplayer in older versions.
