### ISSUE TITLE
Fabric version for 1.16 (please)

### ISSUE THREAD

**Issue by the-r3dacted** [blay09/ClientTweaks#63]
I like this mod, I've been using it in 1.12.2 for a while, but I've finally upgraded to 1.16.5 with Fabric. I have my game near perfect, but I'm missing a couple optional but nice to have mods (like this one). I would love it if this mod has a Fabric 1.16.5 release.

**Comment by BlayTheNinth** [comment]
Minecraft 1.16 is no longer supported
