### ISSUE TITLE
Better compat with Physics mod

### ISSUE THREAD

**Issue by ChromaPIE** [blay09/ClientTweaks#64]
That sounds strange but let me explain. It's a simple but annoying issue.

The volume sliders ClientTweaks adds to the pause screen is overlapping the config button added by Physics mod. I can still click it but it makes the pause menu look so weird and lame.

I don't actually know if it can be fixed on your side but I'm just reporting it here.

**Comment by BlayTheNinth** [comment]
There is standardized places for config buttons in both Forge and Fabric that the Physics mod should be using. It's not really something I want to go out of my way to add special cases for considering the button shouldn't be there in the first place.

However, you can disable the volume sliders in the Client Tweaks settings.

**Comment by ChromaPIE** [comment]
Yea I've already done that. Thanks for the support anyways

**Comment by mpustovoi** [comment]
Apparently, there will be no changes from the Physics Mod side either (https://github.com/haubna/PhysicsMod/issues/276)
