### ISSUE TITLE
incompatibility with actually additions

### ISSUE THREAD

**Issue by Inve1951** [blay09/ClientTweaks#7]
[ActuallyAdditions#324](https://github.com/Ellpeck/ActuallyAdditions/issues/324)
looting AA's compost deletes the currently selected item and places a torch when the item is eligible to do so and the torch is taken from the hotbar.

edit: also happens when the torch can't be placed in that location

**Comment by Ellpeck** [comment]
Yea, I have no idea why this happens so I'm just going to hope that it's your problem @blay09 :P

**Comment by blay09** [comment]
I assume this was fixed on Actually Additions' side. Client Tweaks is just simulating a right-click with the torch, it has no way of deleting items as it's client-side-only.
