### ISSUE TITLE
Fabric says Balm is missing even though it's not

### ISSUE THREAD

**Issue by Galabeam** [blay09/ClientTweaks#70]
### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Mod Loader Version

0.14.21

### Mod Version

11.0.0

### Balm Version

7.0.4

### Describe the Issue

![image](https://github.com/TwelveIterationMods/ClientTweaks/assets/68124962/0bd71b60-174d-4ad0-b681-32fc100ec448)

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Sodium

**Comment by chocolatechipcats** [comment]
Silly question: Did you check to make sure you didn't accidentally download the Forge version? I've done the same (albeit in reverse) in the past.

**Comment by Galabeam** [comment]
I downloaded the fabric version.
![image](https://github.com/TwelveIterationMods/ClientTweaks/assets/68124962/1cf9c454-a06c-42f8-8155-7f08e5feb0ec)

**Comment by Galabeam** [comment]
I don't know what happened but I restarted my computer this morning and just now tried running Minecraft and it magically worked, so I have no idea.
