### ISSUE TITLE
Cannot read field "tweaks" because the return value of "net.blay09.mods.clienttweaks.ClientTweaksConfig.getActive()" is null

### ISSUE THREAD

**Issue by ModernGamingWorld** [blay09/ClientTweaks#73]
### Minecraft Version

Other (specify below)

### Mod Loader

Forge

### Mod Loader Version

Forge

### Mod Version

Latest

### Balm Version

Latest

### Describe the Issue

Launched game went to click on my custom server to join and crashed

[crash-2023-09-20_23.45.07-client.txt](https://github.com/TwelveIterationMods/ClientTweaks/files/12680308/crash-2023-09-20_23.45.07-client.txt)

**Comment by BlayTheNinth** [comment]
I would need a full latest.log to resolve this, because this shouldn't be able to happen under normal circumstances. I assume something is going wrong earlier in the loading stage.
