### ISSUE TITLE
Edit sign

### ISSUE THREAD

**Issue by oxodao** [blay09/ClientTweaks#76]
Hi!

In the latest version of the game, right clicking a sign causes an edit gui to be opened.

It would be neat to be able to configure it as you need to Shift+Right click only, or maybe only when using a specific item.

There also used to be a mod that would open the container behind a sign if it was attached on a chest / furnace / ... that could be neat to have too.

I figured out that this would be the most logical mod to implement such features.

If you're OK with this I could possibly create a PR

**Comment by BlayTheNinth** [comment]
Sounds like a sane addition on both parts as long as they're individual tweaks.

**Comment by oxodao** [comment]
The first PR is ready (https://github.com/TwelveIterationMods/ClientTweaks/pull/79)

I've not implemented the second feature as I'm not sure how it should be handled.
If I right click on a sign with the first feature off, it could either edit the sign or pass through to open the container, not sure what the desired behaviour should be

**Comment by oxodao** [comment]
Wontfix as not possible without dirty hacks
