### ISSUE TITLE
Offhand mechanics for lanterns just like for torches

### ISSUE THREAD

**Issue by Damglador** [blay09/ClientTweaks#82]
So walking with lantern in caves is much cooler than with torch with resource pack for 3D lanterns and dynamic lighting, but lantern is often being placed when/where you didn't want to place it.
I think it shouldn't be hard to implement 

Btw awesome mod, just what I was looking for

**Comment by BlayTheNinth** [comment]
You can add lanterns to the `torchItems` config option to have them treated the same as torches.
