### ISSUE TITLE
Torch placement restriction doesn't work

### ISSUE THREAD

**Issue by Damglador** [blay09/ClientTweaks#85]
### Minecraft Version

1.21

### Mod Loader

Fabric

### Mod Loader Version

0.15.11

### Mod Version

21.0.2

### Balm Version

21.0.10

### Describe the Issue

I tested the feature on fabric for 1.20.6 and 1.20.4 and 1.21 in creative and survival with every offhand torch setting enabled, torch in the list of torches and 1 torch in left hand. Placement of torches is slowed, but not completely disabled. Balm is installed.
With 1 torch it says "Out of torches" but still places the torch (or lantern) with slight delay or two clicks.
It works on 1.20.1 Forge fine.

### Logs

https://mclo.gs/LiiUZR4

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Tested without them and still doesn't work

**Comment by BlayTheNinth** [comment]
Fixed in latest Balm
