### ISSUE TITLE
invisible dirt under bamboo bug

### ISSUE THREAD

**Issue by MarkHarrisMedia** [blay09/ClientTweaks#88]
### Minecraft Version

1.21

### Mod Loader

Fabric

### Mod Loader Version

1.21

### Mod Version

21.0.2

### Balm Version

21.0.14

### Describe the Issue

when I installed client tweaks 21.0.2 it made all bamboo bugged by making the top of the dirt underneath invisible like xray vision.... Not cool, so I just uninstalled yet.

### Logs

no log

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

no

**Comment by BlayTheNinth** [comment]
can't reproduce 
![image](https://github.com/user-attachments/assets/8f89c18e-8b60-462d-96a5-02e32636511a)
